apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-task.fullname" . }}
  labels:
    {{- include "test-task.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "test-task.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "test-task.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: AUTHOR
              value: {{ .Values.author }}
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
